config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # "As a guest user, I want to search a product type"
  # get "/products" => "products#index"
  resources :products, only: [:index]
  # "As a guest user, I want to select multiple stores"
  get "/preferences" => "pages#preferences"

  # "As a guest user, I want to update the stores I selected"
  patch "/preferences" => "pages#update_preferences"

  # "As a guest user, I want to view the items in my list"
  get "/list_items" => "list_items#index"

  get 'about', to: 'pages#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_prices
  has_many :stores, through: :product_prices

  validates :name, :brand, :weight, presence: true

end

app/models/product_price.rb
class ProductPrice < ApplicationRecord
  belongs_to :product
  belongs_to :store

  validates :price, presence: true
  # validates :scraping_date, presence: true
  include PgSearch::Model
  pg_search_scope :search_by_name_and_brand,
                   associated_against: { product: %i[name brand] }

  def percentage(data)
    lowest_product = data[:pp]
    lowest_price = lowest_product.price.delete('$').to_f
    match = lowest_product.product.price_per_100_unit.match(/\$([0-9]*\.?[0-9]+)\/([0-9]+)(\w+)/)
    price = match[1].to_f
    quantity = match[2].to_i
    unit = match[3]
    initial_value = lowest_price
    final_value = data[:final_value]
    associated_value = price
    percentage_increase = ((final_value - initial_value) / initial_value) * 100
    x = (associated_value * (1 + (percentage_increase / 100))).round(2)
    hash = {
      price: final_value,
      lowest_price: x,
      quantity: quantity,
      unit: unit
    }
    return hash
  end

  def average_price
    pp = ProductPrice.where(product: product, store: store)
    sum = 0
    pp.each do |data|
      sum += data.price.delete('$').to_f
    end
    hash = {
      pp: pp.first,
      final_value: (sum / pp.size).round(2)
    }
    # data = percentage(hash)
    return percentage(hash)

  end

  ####################################################################################
  # These methods will only work that way because of the way we implement our seeds.
  # For the future, it will be beneficial to make changes to these methods.
  ####################################################################################

  def highest_price
    # highest_price_product = pp.max_by do |product|
    # product.price
    # end
    pp = ProductPrice.where(product: product, store: store)
    highest_price_product = pp.last
    hash = {
      pp: pp.first,
      final_value: highest_price_product.price.delete('$').to_f
    }

    data = percentage(hash)
    return data
  end

  def lowest_price
    # highest_price_product = pp.min_by do |product|
    #   product.price
    # end
    pp = ProductPrice.where(product: product, store: store)
    highest_price_product = pp.first
    return highest_price_product.price
  end

  def data_for_graph
    pp = ProductPrice.where(product: product, store: store)
    data = pp[1..].map do |d|
      d.price.delete('$').to_f
    end
    data = data.shuffle
    data << pp[0].price.delete('$').to_f
    return data
  end
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :product_prices
  has_many :products, through: :product_prices

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController

  def index
  end

  def new
  end

  def create
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @products = Product.includes(:stores, :product_prices).order("RANDOM()").limit(6).all
    @trending_lows = Product.order("RANDOM()").limit(24).all
    if params[:query].present?
      @products = Product.search_by_name_and_brand(params[:query])
    end
    @current_page = params[:page]&.to_i || 1
    @products_per_page = 3
    @total_pages = (@products.size.to_f / @products_per_page).ceil

  end

  def preferences
  end

  def update_preferences
  end

  def about
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @product_prices = ProductPrice.all
    sort_order = params[:sort_order] || "asc"
    if params[:query].present?
      @product_prices = @product_prices.search_by_name_and_brand(params[:query])
      @product_prices = @product_prices.group_by { |p| p.product_id }.map { |_product_id, prices| prices.first }
      @product_prices = @product_prices.sort_by { |p| p.price }
      @product = @product_prices[0]
    end
    if params[:sort_by] == "price"
    @product_prices = @product_prices.sort_by { |p| p.price }
    @product_prices.reverse! if sort_order == "desc"
    end
    if params[:sort_by] == "price_per_100_unit"
      @product_prices = @product_prices.sort_by { |p| p.product.price_per_100_unit }
      @product_prices.reverse! if sort_order == "desc"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Grrunch" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <script src="https://unpkg.com/feather-icons"></script>
  </head>



  <body>

    <%= yield %>

     <script>
      feather.replace();
    </script>
  </body>
</html>

app/views/pages/about.html.erb
<%= render "shared/navbar" %>

<div class="container-left-align">
  <%= render "shared/search_bar" %>
</div>

<div class="container-about">
  <h1>About Us</h1>

  <div class="heading">
    At Grrunch, we've got one thing keeping us up at night (besides snacks): the jaw-dropping,<span class="highlight">skyrocketing price of groceries</span>
    Luckily, we've got <span class="highlight-green">marketing superpowers.</span> We see through <span class="highlight-purple"> sneaky tactics and cut through the fluff.</span>
  </div>

  <div class="heading">
    Wave goodbye to sponsored products, misaligned targeting ads, and no more SEM promotional algorithms!
  </div>

  <div class="heading">
    <span class="highlight">Shop Smart with Grrunch!</span>
  </div>


</div>

<!--
  <div class="container-2-col">
    <img src="https://res.cloudinary.com/diwuyv3c8/image/upload/v1734040123/sem_sbw5as.svg">
    <p>There are certainly contributing factors, such as the pandemic and the rise in fuel and energy costs, but here we will focus on one we can act on: SEM strategies.</p>

  </div>
-->






</div>

app/views/pages/home.html.erb
<%= render "shared/navbar" %>

<div class="container-left-align">
  <%= render "shared/search_bar" %>
</div>


<div class="container">
  <!--Carrousel -->
  <div class="carousel">
    <div class="carousel__track-container">
      <ul class="carousel__track">
        <li class="carousel__slide current-slide">
          <img src="https://res.cloudinary.com/diwuyv3c8/image/upload/v1733344581/carrousel-01_tbu0hf.svg" class="carousel__image">
        </li>
        <li class="carousel__slide">
          <img src="https://res.cloudinary.com/diwuyv3c8/image/upload/v1733344584/carrousel-02_q7nmko.svg" class="carousel__image">
        </li>
        <li class="carousel__slide">
          <img src="https://res.cloudinary.com/diwuyv3c8/image/upload/v1733344582/carrousel-03_jesk6m.svg" class="carousel__image">
        </li>
      </ul>
    </div>



    <div class="carousel__nav">
      <button class="carousel__indicator current-slide"></button>
      <button class="carousel__indicator"></button>
      <button class="carousel__indicator"></button>
    </div>
  </div>
  <!--End of Carrousel -->

  <div class="container-main container-main--purple">
    <div class="inner-container-main">

      <div class="container-title">
        <img src="https://res.cloudinary.com/diwuyv3c8/image/upload/v1733783819/status-lowest_obdp8y.svg" alt="">
        LOWEST RECORDED TODAY
      </div>

      <div class="container-p">
        Food items that reached their lowest recorded across banners as of today.
      </div>

      <div class="product-carousel relative" data-controller="carousel" data-total-pages=<%= (@products.size.to_f / 3).ceil %>>
        <%# LEFT ARROW %>
        <button class="carousel-nav carousel-prev <%= 'hidden' if @current_page == 1 %>" data-action="click->carousel#previous">
          <i data-feather="chevron-left"></i>
        </button>

        <div class="product-card-container">
          <% @products.each_slice(3).with_index(1) do |page_products, index| %>

            <div class="product-page <%= 'hidden' unless index == @current_page %>" data-page="<%= index %>">
              <% page_products.each do |product| %>
                <%= render "shared/product_card_purple" , product: product %>
              <% end %>
            </div>

          <% end %>
        </div>

        <%# RIGHT ARROW %>
        <button class="carousel-nav carousel-next <%= 'hidden' if @current_page == (@products.size.to_f / 3).ceil %>" data-action="click->carousel#next">
          <i data-feather="chevron-right"></i>
        </button>
      </div>

    </div>
  </div>

  <div class="container-main container-main--green">
    <div class="inner-container-main">
      <div class="container-title">
        <%= image_tag "greendot.svg" , width: 12 %>
        TRENDING LOW
      </div>

      <div class="container-p">
        Food items that reached below their average price
      </div>

      <div class="product-carousel relative" data-controller="carousel" data-total-pages=<%= (@products.size.to_f / 3).ceil %>>
        <%# LEFT ARROW %>
        <button class="carousel-nav carousel-prev <%= 'hidden' if @current_page == 1 %>"
          data-action="click->carousel#previous">
          <i data-feather="chevron-left"></i>
        </button>

        <div class="product-card-container">
          <% @trending_lows.each_slice(3).with_index(1) do |page_products, index| %>

            <div class="product-page <%= 'hidden' unless index == @current_page %>" data-page="<%= index %>">
              <% page_products.each do |product| %>
                <%= render "shared/product_card_green" , product: product %>
              <% end %>
            </div>

          <% end %>
        </div>

        <%# RIGHT ARROW %>
        <button class="carousel-nav carousel-next <%= 'hidden' if @current_page == (@products.size.to_f / 3).ceil %>"
          data-action="click->carousel#next">
          <i data-feather="chevron-right"></i>
        </button>

      </div>
  </div>
</div>

app/views/products/index.html.erb
<%= render "shared/navbar" %>
<div class="container-left-align">
  <%= render "shared/search_bar" %>
  <div class="display-flex">
    <%= render "shared/product_card_product_page" %>
    <div class="product-card product-card__bloc-03">
      <%= render "shared/echart", unique_id: "product-#{@product.id}", product: @product.product %>
    </div>
  </div>
</div>

<%= render "shared/product_table" %>

app/views/shared/_DONOTUSEnavbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_carousel.html.erb
<div class="carousel">
      <div class="carousel__track-container">
        <ul class="carousel__track">
          <li class="carousel__slide current-slide">
            <img src="https://res.cloudinary.com/diwuyv3c8/image/upload/v1733344581/carrousel-01_tbu0hf.svg"
              class="carousel__image">
          </li>
          <li class="carousel__slide">
            <img src="https://res.cloudinary.com/diwuyv3c8/image/upload/v1733344584/carrousel-02_q7nmko.svg"
              class="carousel__image">
          </li>
          <li class="carousel__slide">
            <img src="https://res.cloudinary.com/diwuyv3c8/image/upload/v1733344582/carrousel-03_jesk6m.svg"
              class="carousel__image">
          </li>
        </ul>
      </div>



      <div class="carousel__nav">
        <button class="carousel__indicator current-slide"></button>
        <button class="carousel__indicator"></button>
        <button class="carousel__indicator"></button>
      </div>
    </div>

app/views/shared/_echart.html.erb
<div id="chart-<%= unique_id %>" style="width: 300px;height:260px;">
  <script type="text/javascript">
    var myChart = echarts.init(document.getElementById('chart-<%= unique_id %>'));
    var data = "<%= product.product_prices[0].data_for_graph %>"
    var parsedData = JSON.parse(data);
    var maxValue =  Math.round(Math.max(...parsedData) + 4);
    var option = {
        grid: {
          top: 20,
          bottom: 0,
          left: 10,
          right: 10,
          containLabel: true
        },
        xAxis: {
          type: 'category',
          data: ['Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Today'],
          axisLine: {
            show: true,
            lineStyle: {
              color: '#000000',
              width: 1
            }
          },
          axisTick: {
            show: false
          }
        },
        textStyle: {
          fontFamily: 'Open Sans',
          fontSize: 8,
          color: '#000000',
        },
        yAxis: {
          min: 0,
          max: maxValue,
          interval: 4,
          axisLine: {
            lineStyle: {
              color: '#000000',
              width: 2
            }
          },
          splitLine: {
            show: false
          },
          axisLabel: {
            formatter: function(value) {
              return '$' + value;
            }
          }
        },
        series: [
          {
            data: parsedData,
            type: 'line',
            lineStyle: {
              color: '#9646FF'
            },
            showSymbol: false,
            symbolSize: 8,
            areaStyle: {
              color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
                {
                  offset: 0,
                  color: 'rgba(150, 70, 255, 0.7)'  // More opaque red at the top
                },
                {
                  offset: 1,
                  color: 'rgba(150, 70, 255, 0.1)'  // More transparent red at the bottom
                }
              ])
            },
            markPoint: {
              symbol: 'circle',
              symbolSize: 8,
              itemStyle: {
                color: '#9646FF'
              },
              data: [
                {
                  coord: [6, parsedData[6]]
                }
              ]
            }
          }
        ]
      };
    myChart.setOption(option);
  </script>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar">

  <%# <a href="www.grrunch.com" class="navbar__logo"> %>
  <%= link_to root_path do %>
    <img src="https://res.cloudinary.com/diwuyv3c8/image/upload/v1733093390/grrunch-logo-text_yceq4n.svg"
         width="80%"
         alt="Grrunch Logo">
  <% end %>

  <ul class="navbar__menu">
    <li class="navbar__item">

      <div class="link">
        <i data-feather="map-pin"></i>
        <span>See selected stores</span>
      </div>

      <div class="link">
        <span>
          <%= link_to "About us", about_path, class: "link-anchor" %>
      </span>
      </div>

      <li class="navbar__item">
        <button class="btn-secondary btn-secondary--dashed">My shopping list</button>
      </li>

       <button class="btn-primary btn-primary--white">Sign in</button>
       <button class="btn-primary">Sign up</button>


    </li>
  </ul>
</nav>

app/views/shared/_product_card_green.html.erb
<div class="product-card-hrz">
  <!-- Bloc-01 -->
  <div class="product-card-hrz__bloc-01">
    <div class="product-card-hrz__bloc-01__col-left">
      <h6 style="overflow: hidden;text-overflow: ellipsis; max-width: 200px;white-space: nowrap;">
        <% @thrid_product = ProductPrice.where(product: product)[2] %>

        <%= product.name %>
      </h6>
      <div class="price-weight">
        <%= @thrid_product.product.weight %>
      </div>
    </div>

    <div class="product-card-hrz__bloc-01__col-right">
      <h6>
        <% latest_price = product.product_prices[0] %>
        <%= @thrid_product.price %>
      </h6>
      <div class="price-weight">
        <%= @thrid_product.product.price_per_100_unit %>
      </div>
    </div>
  </div>

  <!-- Bloc-02 -->
  <div class="product-card-hrz__bloc-02">
    <div class="section-01"> <!-- Container left -->
      <div class="product-card-hrz__bloc-02__container-left">
        <img src="<%= @thrid_product.product.img_url %>">
      </div> <!-- Container right -->
      <div class="product-card-hrz__bloc-02__container-right"> <!-- Column 1 -->
        <div class="price-column">
          <div class="price-item">
            <div class="status-dot status-dot-highest"></div>
            <div class="price-content">
              <% @highest_price = product.product_prices[0].highest_price %>
              <div class="price-title">Highest $<%= @highest_price[:price] %></div>
              <div class="price-weight">$<%= @highest_price[:lowest_price] %>/<%= @highest_price[:quantity] %> <%= @highest_price[:unit] %></div>
            </div>
          </div>

          <div class="price-item">
            <div class="status-dot status-dot-lowest"></div>
            <div class="price-content">
              <% @lowest_price = ProductPrice.find_by(product: product) %>
              <div class="price-title">Lowest <%= @lowest_price.price %></div>
              <div class="price-weight">
                <%= product.price_per_100_unit %>
              </div>
            </div>
          </div>
        </div>
         <!-- Column 2 -->
        <div class="price-column">
          <div class="price-item">
            <div class="status-dot status-dot-avg"></div>
            <div class="price-content">
              <% @average_price = product.product_prices[0].average_price %>
              <div class="price-title">Average $<%= @average_price[:price] %></div>
              <div class="price-weight">$<%= @average_price[:lowest_price] %>/<%= @average_price[:quantity] %> <%= @average_price[:unit] %></div>
              <div class="product-card__bloc-05">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_product_card_product_page.html.erb
<div class="product-card-hrz">
  <!-- Bloc-01 -->
  <div class="product-card-hrz__bloc-01">
    <div class="product-card-hrz__bloc-01__col-left">
      <h6 style="overflow: hidden;text-overflow: ellipsis; max-width: 200px;white-space: nowrap;">
        <%= @product.product.name %>
      </h6>
      <div class="price-weight">
        <%= @product.product.weight %>
      </div>
    </div>

    <div class="product-card-hrz__bloc-01__col-right">
      <h6>
        <% latest_price = @product.product.product_prices[0] %>
        <%= latest_price&.price %>
      </h6>
      <div class="price-weight">
        <%= @product.product.price_per_100_unit %>
      </div>
    </div>
  </div>
  <!-- Bloc-02 -->
  <div class="product-card-hrz__bloc-02">
    <div class="section-01"> <!-- Container left -->
      <div class="product-card-hrz__bloc-02__container-left">
        <img src="<%= @product.product.img_url %>">
      </div> <!-- Container right -->
      <div class="product-card-hrz__bloc-02__container-right"> <!-- Column 1 -->
        <div class="price-column">
          <div class="price-item">
            <div class="status-dot status-dot-highest"></div>
            <div class="price-content">
              <% @highest_price = @product.product.product_prices[0].highest_price %>
              <div class="price-title">Highest $<%= @highest_price[:price] %></div>
              <div class="price-weight">$<%= @highest_price[:lowest_price] %>/<%= @highest_price[:quantity] %> <%= @highest_price[:unit] %></div>
            </div>
          </div>

          <div class="price-item">
            <div class="status-dot status-dot-lowest"></div>
            <div class="price-content">
              <% @lowest_price = ProductPrice.find_by(product: @product.product) %>
              <div class="price-title">Lowest <%= @lowest_price.price %></div>
              <div class="price-weight">
                <%= @product.product.price_per_100_unit %>
              </div>
            </div>
          </div>
        </div>
        <!-- Column 2 -->
        <div class="price-column">
          <div class="price-item">
            <div class="status-dot status-dot-avg"></div>
            <div class="price-content">
              <% @average_price = @product.product.product_prices[0].average_price %>
              <div class="price-title">Average $<%= @average_price[:price] %></div>
              <div class="price-weight">$<%= @average_price[:lowest_price] %>/<%= @average_price[:quantity] %> <%= @average_price[:unit] %></div>
              <div class="product-card__bloc-05">
                <div class="link">
                  <span>More details</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_product_card_purple.html.erb
<div class="product-card">
  <div class="product-card__bloc-01">
    <div class="product-card__bloc-01__col-left">
      <h6>
        <%= product.name %>
      </h6>
      <p>
        <%= product.weight %>
      </p>
    </div>
    <div class="product-card__bloc-01__col-right">
      <i data-feather="map-pin"></i>
      <div class="store">
        <%= product.stores.first&.name %>
      </div>
    </div>
  </div>

  <div class="product-card__bloc-02">
    <div class="product-card__bloc-02__col-left">
      <img src="<%= product.img_url %>">
    </div>
    <div class="product-card__bloc-02__col-right">
      <% latest_price=product.product_prices[0] %>
        <h6>
          <%= latest_price&.price %>
        </h6>
        <p>
          <%= product.price_per_100_unit %>
        </p>
    </div>
  </div>

  <div class="product-card__bloc-03">
    <%= render "shared/echart" , unique_id: "product-#{product.id}" , product: product%>
  </div>

  <div class="product-card__bloc-04">
    <div class="row-01">
      <div class="status-dot-highest"></div>
      <div class="row-01-left">
        <% @highest_price=product.product_prices[0].highest_price %>
          <div class="price-title">Highest $<%= @highest_price[:price] %>
          </div>
          <div class="price-weight">$<%= @highest_price[:lowest_price] %>/<%= @highest_price[:quantity] %>
                <%= @highest_price[:unit] %>
          </div>
      </div>
      <div class="status-dot-avg"></div>
      <div class="row-01-right">
        <% @average_price=product.product_prices[0].average_price %>
          <div class="price-title">Average $<%= @average_price[:price] %>
          </div>
          <div class="price-weight">$<%= @average_price[:lowest_price] %>/<%= @average_price[:quantity] %>
                <%= @average_price[:unit] %>
          </div>
      </div>
    </div>
    <div class="row-02">
      <div class="status-dot-lowest"></div>
      <div class="row-01-left">
        <% @product_price=ProductPrice.find_by(product: product) %>
          <div class="price-title">Lowest <%= @product_price.price %>
          </div>
          <div class="price-weight">
            <%= product.price_per_100_unit %>
          </div>
      </div>
    </div>
  </div>
  <div class="product-card__bloc-05">
    <button class="btn-secondary btn-secondary--dashed">
      Add to list
      <i data-feather="plus-circle"></i>
    </button>
    <div class="link">
      <span>More details</span>
    </div>
  </div>
</div>

app/views/shared/_product_table.html.erb
<%= turbo_frame_tag :product_table do %>
  <% if @product_prices.any? %>
    <table class="product-table cellSpacing='0'">
      <thead>
        <tr>
          <th></th>
          <th></th>
          <th>Product Name</th>
          <th>Store</th>
          <th>Brand</th>
          <th>Weight</th>
          <th>
            <div class="display-flex align-center">
              <p>Price Ea.</p>
              <%= button_to products_path, params: {query: params[:query],
                                                    sort_by: "price",
                                                    sort_order: params[:sort_order] == "asc" ? "desc" : "asc"},
                                           method: :get, class: "default btn-filter",  data: { turbo: false } do %>
                <i data-feather="filter"></i>
              <% end %>
            </div>
          </th>

          <th>
            <div class="display-flex align-center">
              <p>Price/Quantity</p>
              <%= button_to products_path, params: {query: params[:query],
                                                    sort_by: "price_per_100_unit",
                                                    sort_order: params[:sort_order] == "asc" ? "desc" : "asc"},
                                           method: :get, class: "default btn-filter",  data: { turbo: false } do %>
                <i data-feather="filter"></i>
              <% end %>
            </div>
          </th>
          <th>Add to my list</th>
        </tr>
      </thead>

      <tbody>
        <% @product_prices.each do |product_price| %>
          <tr>
            <td><i class="fa-solid fa-circle small-icon" style="color: #96e696;"></i></td>
            <td><img src=<%= product_price.product.img_url %> alt="" style="width:60px; height:48px;"></td>
            <div class="overflow"><td><%= product_price.product.name %></td></div>
            <td><%= product_price.store.name%></td>
            <td><%= product_price.product.brand %></td>
            <td><%= product_price.product.weight %></td>
            <td class="price-cell"><%= product_price.price %></td>
            <td class="price-cell"><%= product_price.product.price_per_100_unit %></td>
            <td class="action-cell">+</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <em>Sorry, no food found.</em>
  <% end %>
<% end %>

app/views/shared/_search_bar.html.erb
<div class="search">
  <i data-feather="search" class="search__icon"></i>

  <%= form_with url: products_path, method: :get, class: "search__form" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "search__input",
      placeholder: "Search food items..."
    %>
  <% end %>
</div>